_target_: vocoders.transforms.HifiGANMelSpectrogramm
sample_rate: 24000
n_fft: 1024
win_length: 960
hop_length: 240
power: 1
f_min: 63
f_max: 12000
n_mels: 80
mel_scale: "slaney"
norm: "slaney"
center: false
